#ifndef grammartypes_H
#define grammartypes_H 

typedef enum gtypes {IF, MAIN, PROGRAM, ELSE, WHILE, FOR, VAR, FUNCTION, CLASS, EQUAL, OR, AND, VARIABLE, NUMBER, STRING, COMMENT,
ENDofINPUT, OPAREN, CPAREN, COMMA, PLUS, TIMES, MINUS, DIVIDES, LESSTHAN, GREATERTHAN, ASSIGN, SEMICOLON, MOD, EXP, OBRACE,
 CBRACE, DOT, UNKNOWN, UMINUS, GLUE, BINARY, LIST, STATEMENTS, FUNCTIONCALL,UNARY,OPERATOR, LOGICALOPERATOR,STATEMENT,TABLE,ENV_TYPE,
CLOSURE, BOOLEAN, UNDECLARED, ARRAY, NEWLINE,NEWTAB, ANON, OBRACKET, CBRACKET,ANONCALL,NOT,NIL
} GTYPE;

const char* printG(int);
const char* printINPUT(int);
#endif 
